### ISSUE TITLE
springboot 高版本下问题

### ISSUE THREAD

**Issue by robben999** [allurx/desensitization-spring-boot#15]
在springboot 2.3.2版本下，SpringApplicationRunListener#running 方法先于AutoConfiguration 执行，导致SPRING_APPLICATION_HOLDER.get()获取值为null

**Comment by allurx** [comment]
@robben999 spring-boot已经升级至最新的2.6.3，添加desensitization-spring-boot-starter最新依赖即可生效
```xml
<dependency>
  <groupId>red.zyc.boot</groupId>
  <artifactId>desensitization-spring-boot-starter</artifactId>
  <version>1.0.8</version>
</dependency>
```
