### ISSUE TITLE
springboot 2.7.3以上版本，无法使用

### ISSUE THREAD

**Issue by githubhyq19** [allurx/desensitization-spring-boot#18]
针对springboot 2.7.3的springboot项目，无法使用这个依赖，因为无法实现bean的自动注入。
![image](https://user-images.githubusercontent.com/49023270/230256494-2cc5b0e1-db1c-4310-90a4-c3010ba2070c.png)

**Comment by allurx** [comment]
你把工程clone到本地，然后把[pom.xml](https://github.com/Allurx/desensitization-spring-boot/blob/master/pom.xml)里面的`spring-boot.version`属性升级到2.7.3，最后自己跑一下[desensitization-spring-boot-samples](https://github.com/Allurx/desensitization-spring-boot/tree/master/desensitization-spring-boot-samples)下面的单元测试看看是不是还会出现上面那段异常提示，我本地测试没有问题。

**Comment by githubhyq19** [comment]
- 说明
我的springboot项目是3.7.3的，引入下面的依赖，就出现错误了，主要好像是创建bean失败了
```
<dependency>
  <groupId>red.zyc.boot</groupId>
  <artifactId>desensitization-spring-boot-starter</artifactId>
  <version>1.0.8</version>
</dependency>
```
- 错误信息：
Error creating bean with name 'desensitizationAdvisor' defined in class path resource [red/zyc/desensitization/spring/boot/autoconfigure/DesensitizationAutoConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.aop.Advisor]: Factory method 'desensitizationAdvisor' threw exception; nested exception is java.lang.IllegalArgumentException: 无法获取SpringApplication！当前应用可能不是spring-boot工程。
- 实际情况
本地好像是可以跑起来的，你可以创建一个springboot项目，引入上面这个maven依赖试试，好想就不行了。

**Comment by allurx** [comment]
你在[SpringBootMainApplicationClassRunListener.java](https://github.com/Allurx/desensitization-spring-boot/blob/9b8d6f0860137106102bc1db941f9a8510677895/desensitization-spring-boot-autoconfigure/src/main/java/red/zyc/desensitization/boot/autoconfigure/SpringBootMainApplicationClassRunListener.java#L44)、[DesensitizationAutoConfiguration](https://github.com/Allurx/desensitization-spring-boot/blob/9b8d6f0860137106102bc1db941f9a8510677895/desensitization-spring-boot-autoconfigure/src/main/java/red/zyc/desensitization/boot/autoconfigure/DesensitizationAutoConfiguration.java#L69)这里打上断点，debug启动看看有没有走到这里，理论上应该会**先后**进入到上面两个类的断点上，将SpringApplication这个启动类存入当前线程的ThreadLocal中，如果拿不到SpringApplication就会抛出你上面这个异常，正常的spring-boot项目应该是不会有问题的。你自己调试一下看看问题出在哪里。如果还是解决不了，方便的话请在你自己github主页上传一份你项目的简单demo（只需要包含你自己项目启动流程的架构就行）

**Comment by doupeng19940218** [comment]
这个问题是因为springcloud 容器会清掉ThreadLocal中SpringApplication。

**Comment by allurx** [comment]
> 这个问题是因为springcloud 容器会清掉ThreadLocal中SpringApplication。

真的假的，有出处吗
