### ISSUE TITLE
Configuration property description should not contain Javadoc tags

### ISSUE THREAD

**Issue by snicoll** [allurx/desensitization-spring-boot#6]
Thank you for your work on the starter.

[As documented in the reference guide](), field javadoc for `@ConfigurationProperties`-annotated type [should not contain javadoc tags](https://github.com/Allurx/desensitization-spring-boot/blob/1d5ef32173fd886684b2b196a8d48d0cff1edd0c/desensitization-spring-boot-autoconfigure/src/main/java/red/zyc/desensitization/spring/boot/autoconfigure/DesensitizationProperties.java#L28-L39) as those aren't processed by the annotation processor. 

Please change that to be a succinct description rather and move the more detailed description to the `README` or some reference guide.

**Comment by allurx** [comment]
Thank you for your reminder, I will move the description to the java documentation of the class in the next release.
